### ISSUE TITLE
CFO Badge clips long titles

### ISSUE THREAD

**Issue by ToxicBakery** [cforlando/cforlando.github.io#1]
Chrome 48.0.2564.97
OS X 10.11.13

At particular resolutions, long titles are clipped by the absolute positioned banner. I tried playing with the margins via the clever 'ex' hack being used but I was unable to find a combination of margins that provided a good look while avoiding the clipping issue.

Given this, my recommendation is that we stop positioning the CFO logo and move it to a more permanent header expanding the entire top bar. Alternately, we can use media queries to clean it up a bit for various screen sizes as well.

![screen shot 2016-02-02 at 10 58 20 pm](https://cloud.githubusercontent.com/assets/1614281/12772670/52c4685a-ca01-11e5-93e9-6407355360b1.png)

**Comment by akozlik** [comment]
We're talking about migrating over to the way Code for San Francisco manages their site through github.io. Take a look at http://codeforsanfrancisco.org/ and let me know what you think.

**Comment by ToxicBakery** [comment]
That is what OrlandoDevs is doing too. I know it was mentioned as well last night.

https://github.com/OrlandoDevs/orlandodevs.github.io

**Comment by chadmiller** [comment]
Fixed in 4c98838
